(function(){
  const app=document.getElementById('app');
  const games=window.ZAMN_GAMES||[];
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function navTo(path){history.pushState({},'',path);render();window.scrollTo({top:0,behavior:'smooth'})}
  function setSeo(title,description,path,image){document.title=title;let d=document.querySelector('meta[name="description"]');if(d)d.content=description;let c=document.querySelector('link[rel="canonical"]');if(c)c.href='https://zamn-games.vercel.app'+path;}
  function shell(content){return `<div class="top">🎮 ألعاب زامن — ألعاب جماعية عربية</div><nav class="nav"><a href="/" data-link class="brand">زامن</a><input id="q" class="search" placeholder="ابحث عن لعبة..." aria-label="بحث"></nav>${content}<footer class="footer">© ألعاب زامن</footer>`}
  function card(g){return `<a class="card" href="/game/${esc(g.slug)}" data-link><div class="thumb"><img src="${esc(g.image)}" alt="${esc(g.name)}" width="490" height="350" loading="lazy" decoding="async"><span class="rating">⭐ ${esc(g.rating)}</span></div><div class="body"><h3>${esc(g.name)}</h3><div class="desc">${esc(g.description)}</div><div class="tags"><span class="tag">${esc(g.players)}</span><span class="tag">${esc(g.category)}</span>${g.badge?`<span class="tag">${esc(g.badge)}</span>`:''}</div><span class="btn">عرض اللعبة</span></div></a>`}
  function home(){setSeo('ألعاب زامن | ألعاب جماعية عربية','ألعاب جماعية عربية للعائلة والأصدقاء تعمل مباشرة من المتصفح.','/');app.innerHTML=shell(`<section class="hero"><h1>ألعاب زامن</h1><p>ألعاب عربية جماعية للجلسات والعائلة والأصدقاء. افتح اللعبة من المتصفح وابدأ التحدي.</p></section><main class="wrap"><h2 class="section-title">اختر لعبتك</h2><div id="games" class="games">${games.map(card).join('')}</div><div id="empty" class="empty" hidden>ما لقينا لعبة بهذا الاسم.</div></main>`);const q=document.getElementById('q');q.addEventListener('input',()=>{const v=q.value.trim().toLowerCase();const filtered=games.filter(g=>(g.name+' '+g.description+' '+g.category).toLowerCase().includes(v));document.getElementById('games').innerHTML=filtered.map(card).join('');document.getElementById('empty').hidden=filtered.length>0;bindLinks()});bindLinks()}
  function gamePage(slug){const g=games.find(x=>x.slug===slug);if(!g){notFound();return}setSeo(`${g.name} | ألعاب زامن`,g.description,`/game/${g.slug}`,g.image);const shots=(g.screenshots||[]).map((s,i)=>`<img src="${esc(s)}" alt="صورة ${i+1} من ${esc(g.name)}" width="960" height="540" loading="lazy" decoding="async">`).join('');app.innerHTML=shell(`<main class="game-page"><a href="/" data-link class="back">← الرئيسية</a><section class="game-hero"><img src="${esc(g.image)}" alt="${esc(g.name)}" width="800" height="500" decoding="async"><div><div class="tags"><span class="tag">⭐ ${esc(g.rating)}</span><span class="tag">${esc(g.players)}</span><span class="tag">${esc(g.category)}</span></div><h1>${esc(g.name)}</h1><p>${esc(g.description)}</p><strong>${esc(g.price)}</strong><div class="actions"><a class="btn" href="${esc(g.playLink)}" target="_blank" rel="noopener">ابدأ اللعب</a><a class="btn buy" href="${esc(g.buyLink)}" target="_blank" rel="noopener">شراء اللعبة</a></div></div></section>${shots?`<section class="shots"><h2>صور من داخل اللعبة</h2><div class="shot-grid">${shots}</div></section>`:''}<div class="notice">هذه النسخة مخففة للتطوير: تسجيل الدخول والمكتبة وFirebase سنضيفها بعد التأكد أن التصميم والسرعة مناسبين.</div></main>`);bindLinks()}
  function notFound(){app.innerHTML=shell(`<main class="wrap"><div class="empty"><h1>الصفحة غير موجودة</h1><a class="btn" href="/" data-link>العودة للرئيسية</a></div></main>`);bindLinks()}
  function bindLinks(){document.querySelectorAll('[data-link]').forEach(a=>a.onclick=e=>{if(e.metaKey||e.ctrlKey)return;e.preventDefault();navTo(a.getAttribute('href'))})}
  function render(){const m=location.pathname.match(/^\/game\/([^/]+)\/?$/);if(m)gamePage(decodeURIComponent(m[1]));else if(location.pathname==='/'||location.pathname==='/index.html')home();else notFound()}
  window.addEventListener('popstate',render);render();
})();
